### ISSUE TITLE
optimization for stand-alone labs

### ISSUE THREAD

**Issue by mosesmbadi** [PROTO-TYPE-SOLUTIONS/easymed#582]
Since the system will be used by stand-alone labs as well, we need to find a way to add test-requests directly in the lab screen. My proposal here i to add that button on the lab screen. On-click it should provide the interfac to register a patient and create a tst request from the same form.

![image](https://github.com/user-attachments/assets/b15f85ef-b341-4f47-b0a5-8d6c16b7bdfd)

Alternatively, in the patient's screen, we can add option to send directly to lab under options, instead of going through the whole process of creating a New Visit
![image](https://github.com/user-attachments/assets/62e04bf1-6587-4688-b544-2cc048425e62)

**Comment by levy-web** [comment]
using processes you can send straight to the lab and pharmacy
